
<!-- Aside (Left Column) -->
<div id="aside" class="box">

    <?php echo $this->partial('common/formation_submenu.phtml',
                               array('id_formation' => $this->formation['id'],
                                      'type_formateur' => $this->formation['type_formateur']
                                    )
                             );
?>

</div> <!-- /aside -->

<hr class="noscreen" />

<!-- ***************** CONTENT (Right Column) **********************  -->
<div id="content" class="box">

    <!-- System Messages -->
    <h4 class="tit">  Organismes de formation enregistrés &rsaquo; <?php echo $this->formation['intitule']; ?> </h4>
    <!-- Flash Message -->
    <?php echo $this->partial('common/flashMessage.phtml',
                               array('message' => $this->fm, 'status'=>'done')
                             );
    ?>
    
    
    <!-- Liste des formations  -->
    <table class="list">
        <tr>
            <th>Cabinet sélectionné</th>
            <th>Formateur</th>
            <th>&nbsp;</th>
        <?php if($this->formationExterne) { ?>
        <tr>
            <td><?php echo $this->cabinet['organisme']; ?></td>
            <td><?php echo $this->formationExterne['formateur']; ?></td>
            <td class="actions"> 
                <a href="<?php echo $this->url(array('controller' => 'organisme-formation', 'action' => 'edit', 'id_formation'=>$this->formation['id'], 'id_organisme'=>$this->cabinet['id']), null, true); ?>" class="edit">
                    modifier
                </a> &nbsp;
                <a href="" class="delete">
                    supprimer
                </a>
            </td>
        </tr>
        <?php } ?>
    </table>
    
    
    <!-- ACTION BAR -->
    <?php if(!$this->formationExterne) : ?>
    <div class="actionBar">
        <a href="<?php echo $this->url(array('controller' => 'organisme-formation', 'action' => 'add', 'id_formation' =>$this->formation['id']), null, true); ?>" class="add">
           ajouter cabinet
        </a>
    </div>
    <?php endif; ?>
    
    
</div> <!-- /content -->