<?php
    $this->jQuery()->enable();
?>

<div id="content" class="box">

    <!-- System Messages -->
    <h3 class="tit">Enregistrer un cabinet</h3>
   
    <div class="box-content">
        <?php
           $this->form->setAction($this->url(array("controller" => "organisme", "action" => "save-form")));
           echo $this->form;
        ?>
        <div class="cleaner"></div>
    </div>

    <!-- ACTION BAR -->
    <div class="actionBar">
        
        <a href="<?php echo $this->url(array('controller' => 'organisme', 'action' => 'index','id_formation' => $this->idFormation), null, true); ?>" class="list">
           liste des organismes
        </a>        
    </div>
    
</div> <!-- /content -->



