<?php
    echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="fr-FR">
    <head>
        <title>GRH FORMATION</title>
       <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <!-- CSS PAGE -->
       <link rel="stylesheet" media="screen,projection" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/loginForm.css" /> <!-- WRITE YOUR CSS CODE HERE -->
       
       <div id="header">
           <h1>
               <img src="<?php echo $this->baseUrl(); ?>/images/orange.jpg" align="absmiddle"/> &nbsp;&nbsp;
               forage &nbsp;&nbsp;
               <img src="<?php echo $this->baseUrl(); ?>/images/logo_cit.png" align="absmiddle" class="right"/>
          </h1>
           <span>application de gestion des formations OCIT - version 1.0</span>
       </div>
       <div id="box">
           <div class="elements">
               <div class="avatar"></div>
               <?php echo $this->layout()->content; ?>
           </div>
       </div>
   	
        
		


	

</body>
</html>