<div class="formrow">
    <div class="label">
    	<label><?php echo $this->element->getLabel(); ?>:</label>
    </div>
    <div class="field">
    	<?php echo $this->{$this->element->helper}($this->element->getName(), $this->element->getValue(), $this->element->getAttribs(), $this->element->getMultiOptions()); ?>
        <?php if ($this->element->hasErrors()): ?>
            <div class="error">
                <?php echo $this->formErrors($this->element->getMessages()); ?>
            </div>
        <?php endif; ?>
	</div>
</div>
