<div id="content" class="box">

    <!-- System Messages -->
    <h3 class="tit">Modifier Cout indirect de session</h3>
   
    <div class="box-content">
        <?php
         $this->form->setAction($this->url(array("controller" => "session-cout-indirect", "action" => "save-form")));
         echo $this->form;
        ?>
        <div class="cleaner"></div>
    </div>

     <!-- ACTION BAR -->
    <div class="actionBar">
        
        <a href="<?php echo $this->url(array('controller' => 'session-cout-indirect', 'action' => 'index', 'id_formation'=>$this->idFormation ), null, true); ?>" class="list">
            retour cout indirect
        </a>
        
    </div>
     
</div> <!-- /content -->



