<?php
    $this->jQuery()->enable();
?>

<div id="content" class="box">

    <!-- System Messages -->
    <h3 class="tit">Enregistrer un salarié</h3>
   
    <div class="box-content">
        <?php
        $this->form->setAction($this->url(array("controller" => "personnel", "action" => "save-form")));
        echo $this->form;
        ?>
        <div class="cleaner"></div>
    </div>
    
</div> <!-- /content -->



