
<!-- Aside (Left Column) -->
<div id="aside" class="box">

    <?php echo $this->partial('common/formation_submenu.phtml',
                               array('id_formation' => $this->formation['id'],
                                      'type_formateur' => $this->formation['type_formateur']
                                     )
                             );
?>

</div> <!-- /aside -->

<hr class="noscreen" />

<!-- ***************** CONTENT (Right Column) **********************  -->
<div id="content" class="box">

    <!-- System Messages -->
    <h4 class="tit">  Couts direct enregistrés &rsaquo; <?php echo $this->formation['intitule']; ?> </h4>
    <!-- Flash Message -->
    <?php echo $this->partial('common/flashMessage.phtml',
                               array('message' => $this->fm, 'status'=>'done')
                             );
    ?>
    
    
    <!-- Liste des bons de commande  -->
    <table class="list">
        <tr>
            <th>Session du </th>
            <th align='center'>Prélevé sur Budget</th>
            <th align='center'>Montant</th>
            <th>BC</th>
            <th>DA</th>
            <th>Observation</th>
            <th>&nbsp;</th>
        <?php $total = 0; foreach($this->couts_direct as $cd) { ?>
        <tr>
            <td><?php echo $cd['date_debut'].' au '.$cd['date_fin']; ?></td>
            <td align='center'><?php echo $cd['entite'].' '.$cd['annee']; ?></td>
            <td align='center'><?php echo number_format($cd['montant']); $total +=$cd['montant'];?></td>
            <td><?php echo $cd['numero_commande']; ?></td>
            <td><?php echo $cd['numero_da']; ?></td>
            <td><?php echo $cd['observation']; ?></td>
            <td class="actions"> 
                <a href="<?php echo $this->url(array('controller' => 'formation-cout-direct', 'action' => 'edit', 'id_formation'=>$this->formation['id'],'id'=>$cd['id']), null, true); ?>" class="edit">
                    modifier
                </a>&nbsp;
                <!-- 
                <a href="" class="delete">
                    supprimer
                </a>
                -->
            </td>
        </tr>
        <?php } ?>
        <tr class="sub-result">
            <td> Total Couts direct</td>
            <td> &nbsp;</td>
            <td align='center'> <?php echo number_format($total); ?></td>
        </tr>
          
    </table>
    
    
    <!-- ACTION BAR -->
    <div class="actionBar">
        
        <a href="<?php echo $this->url(array('controller' => 'formation-cout-direct', 'action' => 'add', 'id_formation' =>$this->formation['id']), null, true); ?>" class="add">
            nouveau cout
        </a>
        
    </div>
    
    
</div> <!-- /content -->